# baseURL = 'https://example.org/'
title = "FanBig's Blog"
author = "FanBig"
paginate = 5
copyright = "FanBig"
languageCode = 'en'
defaultContentLanguage = "en"
# hasCJKLanguage = true
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]
enableRobotsTXT = false
enableEmoji = true

[menu]
[[menu.main]]
identifier = "post"
name = "Post"
pageRef = "/posts"
weight = 0
[[menu.main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 10

[markup]
_merge = "deep"

# [markup]
# [markup.highlight]
# # lineNos = true
# noClasses = false
# [markup.goldmark]
# [markup.goldmark.renderer]
# unsafe = true
# [markup.goldmark.extensions]
# [markup.goldmark.extensions.cjk]
# enable = true
# eastAsianLineBreaks = true
# escapedSpace = true

[privacy]
[privacy.vimeo]
disabled = false
simple = true

[privacy.twitter]
disabled = false
enableDNT = true
simple = true

[privacy.instagram]
disabled = false
simple = true

[privacy.youtube]
disabled = false
privacyEnhanced = true

[module]
[module.hugoVersion]
extended = false
min = "0.120.0"
